// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This is a placeholder. You should run `flutterfire configure` to generate the real file.
    return const FirebaseOptions(
      apiKey: 'dummy-api-key',
      appId: 'dummy-app-id',
      messagingSenderId: 'dummy-sender-id',
      projectId: 'dummy-project-id',
      storageBucket: 'dummy-storage-bucket',
      iosBundleId: 'com.example.givv',
    );
  }
}
